### ISSUE TITLE
Invalid MEX-file /lib64/libc.so.6: version `GLIBC_2.17' not found

### ISSUE THREAD

**Issue by nehcgnay** [arokem/python-matlab-bridge#200]
Hello, 

I tried to run in python 3.4.3 but it fails to start matlab. 
My OS is CentOS 6.6 x86_64. 
Here is the log:

Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge-0bf7bc3e-1dba-4d4e-8ba8-70b25882f480
Send 'exit' command to kill the server
Invalid MEX-file
'/home/yang.chen/python-matlab-bridge-master/pymatbridge/matlab/messenger.mexa64':
/lib64/libc.so.6: version `GLIBC_2.17' not found (required by
/home/yang.chen/python-matlab-bridge-master/pymatbridge/matlab/messenger.mexa64)

Error in matlabserver (line 7)
messenger('init', socket_address);

............................................................MATLAB session timed out after 60 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yang.chen/python-matlab-bridge-master/pymatbridge/pymatbridge.py", line 225, in start
    raise ValueError("%s failed to start" % self._program_name())
ValueError: MATLAB failed to start
 
Any suggestions are appreciate. Thank you in advance!

**Comment by sev808** [comment]
Hi,
I have the same exact error while trying to run matlab from python by using pymatbridge.
My OS is CentOS 6.5 x86_64, python 2.6.6, Matlab R2013b. 
Did you solve your issue? if so, do you remember how?
Let me know
Thanks by advance
Sev

**Comment by j08lue** [comment]
Same on CentOS 6.7 with Python 2.7 (Anaconda), pymatbridge 0.5.2 installed via

    conda install --channel https://conda.anaconda.org/IOOS pymatbridge

**Comment by Woodstonelee** [comment]
I have the same problem on CentOS release 6.4. According to the log, it looks like pymatbridge requires newer version of glibc, at least v2.17. I checked the glibc on my CentOS, it is only 2.12... and I don't have a root access to upgrade glibc. Not sure if the author can support older version of glibc. I hope it is possible.

**Comment by falaktheoptimist** [comment]
Same on ubuntu 14.04 with python 2.7, pymatbridge 0.5.2. I think, it needs updated glibc (version >2.17)

**Comment by tgarc** [comment]
see issue  #221 for a workaround
