### ISSUE TITLE
failed to start matlab session from a certain location

### ISSUE THREAD

**Issue by verenamueller** [arokem/python-matlab-bridge#226]
hey there, 
I want to start a certain Matlab version cause I just have licence for R2010b but also installed R2013b on my device. So when I start the session with the default command -mlab=Matlab()- it wants to start R2013b, but without licenc I can't use it. And when I try  - mlab=Matlab(executable='C:\Program Files\MATLAB\R2010b\bin\matlab.exe') - the Server starts but nothing happens! 

>Starting MATLAB on ZMQ socket tcp://127.0.0.1:58782
Send 'exit' command to kill the server
............................................................MATLAB session timed out after 60 seconds
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    mlab.start()
  File "C:\Python34\lib\site-packages\pymatbridge-0.6.dev0-py3.4.egg\pymatbridge\pymatbridge.py", line 227, in start
    raise ValueError("%s failed to start" % self._program_name())
ValueError: MATLAB failed to start

I use Windows 7 x64-based PC - python 3.4 - pyzmq 14.7.0

Thanks in advance,
Verena

**Comment by isbadawi** [comment]
Have you tried escaping the backslashes, e.g.

```
'C:\\Program Files\\MATLAB\\R2010b\\bin\\matlab.exe'
```

**Comment by verenamueller** [comment]
Yes, I tried. But it doesn't helped either. Does this command work on Windows anyway?

**Comment by arokem** [comment]
pymatbridge does work with Windows, but setup varies from computer to
computer and it is hard for us to cover all the uses.

We should be doing a release soon, and this might resolve your issues.
