### ISSUE TITLE
Python stalls and throws a Java exception whenever plotting functions are called.

### ISSUE THREAD

**Issue by CosmoJG** [arokem/python-matlab-bridge#244]
As the title states, plotting doesn't seem to work on my system whatsoever. I am running Ubuntu 16.04 with MATLAB R2016a and Python 3.5 installed via Anaconda. I've updated IPython to version 5.1 as well, and zeromq is version 4.1.4.

The error can be replicated by attempting to run either example notebook (matlab_magic.ipynb or pymatbridge.ipynb) or by simply trying to run matlab.plot(x), matlab.bar(x), or any other plotting command after starting a MATLAB server.

Here's the exception:
```
!!!!!!!!
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Unknown Source)
	at com.mathworks.hg.util.OutputHelperProcessingException.<init>(OutputHelperProcessingException.java:17)
	at com.mathworks.hg.util.HGRasterOutputHelper.generateOutput(HGRasterOutputHelper.java:170)
!!!!!!!!
```

**Comment by trummelbummel** [comment]
same here unfortunately! I just bought matlab because the spectrogram function in python mlab was not giving me the correct results. Any ideas on other similar options that don't throw these errors are appreciated as well. I'd need the plots, but I have the feeling that this is my best bet with the new matlab version. I have seen this issue being mentioned as related to the matlab version 2016a. Maybe downgrading matlab is a possibility for now.

**Comment by arokem** [comment]
Yes - I now have Matlab2016 and I am seeing the same issues with plotting.

The MatlabInterpreterError that gets thrown says:

"Images must contain fewer than 2^32 - 1 bytes of data."


It looks like images are getting generated at some unreasonably high
resolution, or something like that:

http://stackoverflow.com/questions/34113784/saving-a-
very-large-image-in-matlab

I am not sure why that's happening, though.

**Comment by CosmoJG** [comment]
@arokem How are you viewing that MatlabInterpreterError?

**Comment by arokem** [comment]
It gets raised by cell 3 in this notebook:

https://github.com/arokem/python-matlab-bridge/blob/master/pymatbridge/examples/matlab_magic.ipynb

**Comment by CosmoJG** [comment]
@arokem All I see is this: http://i.imgur.com/mO2Yu8b.png

**Comment by arokem** [comment]
I see that first, but then after a short wait:

**Comment by arokem** [comment]
![screen shot 2016-08-17 at 3 17 23 pm](https://cloud.githubusercontent.com/assets/118582/17755341/61a73bae-648e-11e6-941e-f42cc1aaa608.png)

**Comment by CosmoJG** [comment]
@arokem Ahh, I see. I guess I should have let the code run a bit longer. What are your thoughts on how to fix it? I've only just started diving into your program so I personally don't have any grand ideas yet.

**Comment by arokem** [comment]
One possible place that might be causing this is the setting of plot
properties:

https://github.com/arokem/python-matlab-bridge/blob/master/pymatbridge/pymatbridge.py#L332-L341

If the API of this changed in Matlab 2016, something in there might cause
plots to blow up.

**Comment by trummelbummel** [comment]
I am not quite sure why the size of the image would be relevant if I'd save my images within the matlab script and do not pass them back to python? Whereas I would like to pass back the computed values to python.

**Comment by arokem** [comment]
I think that something in this setup is causing Matlab to create images
that are unreasonably large when `plot` is called (see the link to SO
above).

**Comment by trummelbummel** [comment]
Ah thank you! I didn't see that.
