### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Gokul115** [arokem/python-matlab-bridge#64]
I have install the pymatbridge but I was unable to open it because I'm getting some errors. Kindly help me out as to how to solve this, since I'm new to programming and not comfortable with ubuntu as well. I'm using Ubuntu 12.04, Matlab version R2013a and python 2.7.3.

> > > from pymatbridge import Matlab
> > > mlab=Matlab(matlab='/usr/local/MATLAB/R2013a/bin/matlab')
> > > mlab.start()

Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge
Send 'exit' command to kill the server
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 135, in start
if (self.is_connected()):
File "/usr/local/lib/python2.7/dist-packages/pymatbridge/pymatbridge.py", line 168, in is_connected
resp = self.socket.recv_string(flags=zmq.NOBLOCK)
File "socket.pyx", line 456, in zmq.core.socket.Socket.getattr (zmq/core/socket.c:4576)
AttributeError: Socket has no such option: RECV_STRING
                        < M A T L A B (R) >
              Copyright 1984-2013 The MathWorks, Inc.
                R2013a (8.1.0.604) 64-bit (glnxa64)
                         February 15, 2013

To get started, type one of these: helpwin, helpdesk, or demo. For product information, visit www.mathworks.com.
Socket created at: ipc:///tmp/pymatbridge

and it got stuck and does nothing.

Regards,
Gokul

**Comment by blink1073** [comment]
Hi @Gokul115, sorry for the delay. This looks like a ZMQ specific error.  Can you post the outcome of:

```bash
$ sudo updatedb
$ locate libzmq.so
```
